version: '3.2'
services:
  gitclient:
    build:
      context: 'docker/gitclient'

  gitserver:
    image: 'catks/gitserver-http'
    volumes:
      - './initial:/var/lib/initial:ro'
    ports:
      - '8080:80'
